// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __QR_scan_am_submuldEe__HH__
#define __QR_scan_am_submuldEe__HH__
#include "simcore_am_1.h"
#include <systemc>

template<
    int ID,
    int NUM_STAGE,
    int din0_WIDTH,
    int din1_WIDTH,
    int din2_WIDTH,
    int dout_WIDTH>
SC_MODULE(QR_scan_am_submuldEe) {
    sc_core::sc_in< sc_dt::sc_lv<din0_WIDTH> >   din0;
    sc_core::sc_in< sc_dt::sc_lv<din1_WIDTH> >   din1;
    sc_core::sc_in< sc_dt::sc_lv<din2_WIDTH> >   din2;
    sc_core::sc_out< sc_dt::sc_lv<dout_WIDTH> >   dout;



    simcore_am_1<ID, 1, din0_WIDTH, din1_WIDTH, din2_WIDTH, dout_WIDTH> simcore_am_1_U;

    SC_CTOR(QR_scan_am_submuldEe):  simcore_am_1_U ("simcore_am_1_U") {
        simcore_am_1_U.din0(din0);
        simcore_am_1_U.din1(din1);
        simcore_am_1_U.din2(din2);
        simcore_am_1_U.dout(dout);

    }

};

#endif //
