# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Desktop/night0717/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_QR_scan_0_0/system_QR_scan_0_0.xci
# IP: The module: 'system_QR_scan_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Desktop/night0717/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_QR_scan_0_0/constraints/QR_scan_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_QR_scan_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Desktop/night0717/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_QR_scan_0_0/system_QR_scan_0_0.xci
# IP: The module: 'system_QR_scan_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Desktop/night0717/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_QR_scan_0_0/constraints/QR_scan_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_QR_scan_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
